name: Build LaTeX document
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: alexander-weichart-cv.tex
          continue_on_error: true
          latexmk_use_xelatex: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "alexander-weichart-cv.pdf"