name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          continue_on_error: true
          latexmk_use_xelatex: true
      - name: Create release
        uses: ncipollo/release-action@v1
          with:
            artifacts: "main.pdf"